---
- hosts: all
  tasks: 
  - name: Create a logical volume of 1G
    lvol:
      vg: vg_sistema
      lv: lv_xdr
      size: 1g

  - name: Create directory
    file:
      path: /opt/traps
      state: directory
      mode: '0755'

  - name: Format ext4 filesystem
    filesystem:
      fstype: ext4
      dev: /dev/vg_sistema/lv_xdr

  - name: mount de xdr filesystem
    mount:
      path: /opt/traps
      src: /dev/vg_sistema/lv_xdr
      fstype: ext4
      state: mounted

  - name: Añadir linea al fstab
    lineinfile:
      path: /etc/fstab
      line: '/dev/mapper/vg_sistema-lv_xdr   /opt/traps     ext4    defaults    1 2'
      backup: yes

  - name: copy rpm to machine
    copy:
      src: /software/XDR/ENAGAS_750_Linux_0109221.rpm
      dest: /tmp/Linux_0109221.rpm
      owner: root
      mode: 0755

  - name: Install dependencies
    yum:
      name: ['selinux-policy-devel', 'ca-certificates', 'glibc', 'openssl']
      state: present
      update_cache: True

  - name: Install package Cortex XDR
    yum:
      name: /tmp/ENAGAS_750_Linux_0109221.rpm
      state: present

  - name: Execute command to configure 
    command: /opt/traps/bin/cytool proxy set "172.16.11.31:8888"

  - name: Restart service 
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: traps_pmd
