---
- hosts: all
  tasks: 
  - name: Create a logical volume of 1G
    lvol:
      vg: vg_sistema
      lv: lv_softw
      size: 1g

  - name: Create directory
    file:
      path: /opt/softw
      state: directory
      mode: '0755'

  - name: Format ext4 filesystem
    filesystem:
      fstype: ext4
      dev: /dev/vg_sistema/lv_softw

  - name: mount filesystem
    mount:
      path: /opt/softw
      src: /dev/vg_sistema/lv_softw
      fstype: ext4
      state: mounted

  - name: Añadir linea al fstab
    lineinfile:
      path: /etc/fstab
      line: '/dev/mapper/vg_sistema-lv_softw   /opt/softw     ext4    defaults    1 2'
      backup: yes

  - name: copy rpm to machine
    copy:
      src: /software/Linux_softw.rpm
      dest: /tmp/Linux_softw.rpm
      owner: root
      mode: 0755

  - name: Install dependencies
    yum:
      name: ['selinux-policy-devel', 'ca-certificates', 'glibc', 'openssl']
      state: present
      update_cache: True

  - name: Install package 
    yum:
      name: /tmp/Linux_softw.rpm
      state: present

  - name: Execute command to configure 
    command: /opt/bin/config_softw set "XX.XX.XX.XX:5555"

  - name: Restart service 
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: softw_srv
